[workspace]
channels = ["conda-forge"]
name = "STREAM"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
start = "jupyter lab"

[dependencies]
python = "3.12.*"
s3fs = ">=2026.2.0,<2027"
xarray = ">=2026.2.0,<2027"
tqdm = ">=4.67.3,<5"
geopandas = ">=1.1.2,<2"
jupyterlab = ">=4.5.5,<5"
pixi-kernel = ">=0.7.1,<0.8"
setuptools = "<70"
pygments = ">=2.19.2,<3"
pyarrow = ">=23.0.1,<24"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
ipyleaflet = ">=0.20.0,<0.21"
ipywidgets = ">=8.1.8,<9"
sidecar = ">=0.8.0,<0.9"

[pypi-dependencies]
hsclient = ">=1.1.6, <2"
